# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dualbooks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learn a new language while reading a book.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://1001ideas.org" # the base hostname & protocol for your site
twitter_username: gewoonm
github_username:  MatthijsZw

# Build settings
markdown: kramdown

collections:
  books:
    output: true
  chapters:
    output: true
